Update estudiantes1718.md
DeustoPWEB/pweb2017 pull request #9
Opened 2017-10-04 09:42 UTC by mjaenh

2017-10-04 10:57 UTC, mirenbz requested changes
Revisa el contenido de tu documento, info aquí abajo

2017-10-04 10:57 UTC, mberasategi commented on estudiantes1718.md
> +- [Franco Gómez, Rocío](http://rofrago.github.io)
Cada uno debéis añadir solamente vuestro propio nombre; @rofrago debería ser quien añada el suyo. Elimina esta línea de tu archivo, y entonces haré merge de tu código en el branch `master`.

2017-10-06 10:11 UTC, mberasategi commented
@mjaenh , he cambiado el título de este pull request para que se refiera más exactamente a los cambios que has hecho tú, porque de lo contrario todos los pull requests que hagáis para añadir vuestros nombres tendrían el mismo título (`Update estudiantes1718.md`). También he visto que el branch sobre el que has trabajado en tu fork rel repositorio se llama `patch-2`, así que quiero aprovechar este mensaje para recordarte que utilices descripciones descriptivas (valga la redundancia) para nombrar tus branches, commits, issues y pull requests; nos hará más fácil a todos estar al tanto de las modificaciones que vayas haciendo. 

Todavía está pendiente la corrección que te pedía en [el mensaje anterior](https://github.com/DeustoPWEB/pweb2017/pull/9#commitcomment-24755447), no dudes en responder en este mismo hilo si necesitas ayuda.

2017-10-08 07:58 UTC, mjaenh commented
Buenos días, lo he cambiado ya pero no me deja hacer pull, ¿que debo hacer
para que me deje realizar los cambios?
Gracias.

El 6 de octubre de 2017, 12:11, Miren Berasategi <notifications@github.com>
escribió:

> @mjaenh <https://github.com/mjaenh> , he cambiado el título de este pull
> request para que se refiera más exactamente a los cambios que has hecho tú,
> porque de lo contrario todos los pull requests que hagáis para añadir
> vuestros nombres tendrían el mismo título (Update estudiantes1718.md).
> También he visto que el branch sobre el que has trabajado en tu fork rel
> repositorio se llama patch-2, así que quiero aprovechar este mensaje para
> recordarte que utilices descripciones descriptivas (valga la redundancia)
> para nombrar tus branches, commits, issues y pull requests; nos hará más
> fácil a todos estar al tanto de las modificaciones que vayas haciendo.
>
> Todavía está pendiente la corrección que te pedía en el mensaje anterior
> <https://github.com/DeustoPWEB/pweb2017/pull/9#commitcomment-24755447>,
> no dudes en responder en este mismo hilo si necesitas ayuda.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DeustoPWEB/pweb2017/pull/9#issuecomment-334715013>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AedX7Yooowmna-fEempS3r3ok8g9s05Wks5spfy_gaJpZM4PtWKy>
> .
>

2017-10-09 07:02 UTC, mberasategi commented
Hola @mjaenh , lo miro mejor cuando esté delante de un ordenador, pero mientras, asegúrate de tus cambios/commits los has hecho sobre el mismo branch del que hiciste el pull request, en este caso `patch-2`. Si es así deberían aparecer aquí automáticamente.

2017-10-09 09:07 UTC, mberasategi commented
Hola otra vez @mjaenh . Lo primero, antes de poder hacer cualquier otra cosa, es actualizar tu copia con los cambios que ha tenido el repositorio desde que hiciste el fork. Para esto tienes que hacer clic en el botón **Merge pull request** en [tu repositorio](https://github.com/mjaenh/pweb2017/pull/1).

2017-10-23 09:41 UTC, mirenbz approved these changes

2017-10-23 09:41 UTC, merged